import { CATALOG_VERSION, type CatalogEntry } from './technology-catalog.contract';

/**
 * The reviewed technology catalogue.
 *
 * Every entry was written by a person and carries the date it was last looked
 * at. That is the whole point: these are the facts a recommendation is allowed
 * to assert, and a fact nobody reviewed is a fact nobody is accountable for.
 *
 * ## Scope
 *
 * Broad rather than exhaustive. It covers the categories the supported project
 * types actually need, with the mainstream choice and the common alternatives in
 * each. It is not a directory of everything that exists — a user who wants
 * something absent types it in, and a custom technology is authoritative
 * without being in here.
 *
 * ## Commercial entries are present on purpose
 *
 * This application must run without paying anyone. The *projects it analyses*
 * are under no such constraint: a client who already runs on AWS, takes payments
 * through Stripe and authenticates with Auth0 has made those decisions, and a
 * tool that refused to name them would be useless to the person writing their
 * proposal. What the application owes them is an honest label — `USAGE_BASED`,
 * `COMMERCIAL` — and a note about what committing implies. See ADR-0028.
 */

const REVIEWED = '2026-08-01';

/** Defaults for the fields most entries do not need to state. */
function entry(input: {
  id: string;
  name: string;
  category: CatalogEntry['category'];
  type: CatalogEntry['type'];
  licence: string;
  costPosture: CatalogEntry['costPosture'];
  maturity: CatalogEntry['maturity'];
  selfHostable: boolean;
  openSource?: boolean;
  managedServiceAvailable?: boolean;
  secondaryCategories?: CatalogEntry['secondaryCategories'];
  aliases?: readonly string[];
  supportedProjectTypes?: CatalogEntry['supportedProjectTypes'];
  incompatibleWith?: CatalogEntry['incompatibleWith'];
  strengths?: readonly string[];
  limitations?: readonly string[];
  operationalComplexity?: CatalogEntry['operationalComplexity'];
  infrastructureBurden?: CatalogEntry['infrastructureBurden'];
  learningBurden?: CatalogEntry['learningBurden'];
  commercialUseNote?: string;
  recommendedVersion?: string;
}): CatalogEntry {
  return {
    id: input.id,
    name: input.name,
    category: input.category,
    secondaryCategories: input.secondaryCategories ?? [],
    aliases: [...(input.aliases ?? [])],
    type: input.type,
    openSource: input.openSource ?? input.costPosture === 'FREE_SELF_HOSTED',
    licence: input.licence,
    commercialUseNote: input.commercialUseNote ?? '',
    selfHostable: input.selfHostable,
    managedServiceAvailable: input.managedServiceAvailable ?? false,
    maturity: input.maturity,
    supportedProjectTypes: input.supportedProjectTypes ?? [],
    incompatibleWith: input.incompatibleWith ?? [],
    strengths: [...(input.strengths ?? [])],
    limitations: [...(input.limitations ?? [])],
    operationalComplexity: input.operationalComplexity ?? 'low',
    infrastructureBurden: input.infrastructureBurden ?? 'low',
    learningBurden: input.learningBurden ?? 'medium',
    costPosture: input.costPosture,
    ...(input.recommendedVersion ? { recommendedVersion: input.recommendedVersion } : {}),
    catalogVersion: CATALOG_VERSION,
    lastReviewed: REVIEWED,
  };
}

const MIT = 'MIT';
const APACHE = 'Apache-2.0';
const FREE = 'FREE_SELF_HOSTED' as const;

export const TECHNOLOGY_CATALOG: readonly CatalogEntry[] = [
  /* ------------------------------------------------------ web frontend */
  entry({
    id: 'react',
    name: 'React',
    category: 'web_frontend',
    type: 'library',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['reactjs', 'react.js'],
    strengths: ['The largest hiring pool of any frontend library', 'Enormous component ecosystem'],
    limitations: ['A library, not a framework — routing, data and build are separate decisions'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'nextjs',
    name: 'Next.js',
    category: 'web_frontend',
    type: 'framework',
    licence: MIT,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    aliases: ['next', 'next.js'],
    secondaryCategories: ['backend'],
    strengths: [
      'Server rendering and static generation without assembling them yourself',
      'Routing, bundling and image handling arrive decided',
    ],
    limitations: ['Opinionated; fighting the framework is expensive'],
    commercialUseNote:
      'Free to self-host under MIT. Vercel hosting is a paid product; nothing requires it.',
    learningBurden: 'medium',
  }),
  entry({
    id: 'vue',
    name: 'Vue',
    category: 'web_frontend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['vuejs', 'vue.js'],
    strengths: ['Gentle learning curve', 'Single-file components keep markup and logic together'],
    limitations: ['Smaller hiring pool than React in most markets'],
    learningBurden: 'low',
  }),
  entry({
    id: 'angular',
    name: 'Angular',
    category: 'web_frontend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Batteries included: DI, forms, routing and HTTP are all decided'],
    limitations: ['Heaviest of the mainstream options', 'Steep initial learning curve'],
    learningBurden: 'high',
  }),
  entry({
    id: 'svelte',
    name: 'Svelte',
    category: 'web_frontend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    aliases: ['sveltekit'],
    strengths: ['Compiles away, so runtime payloads are small'],
    limitations: ['Smaller ecosystem and hiring pool'],
    learningBurden: 'low',
  }),
  entry({
    id: 'astro',
    name: 'Astro',
    category: 'web_frontend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    supportedProjectTypes: ['WEBSITE', 'ECOMMERCE_PLATFORM'],
    strengths: ['Ships almost no JavaScript for content sites', 'Excellent for static publishing'],
    limitations: ['Not intended for heavily interactive applications'],
    learningBurden: 'low',
  }),
  entry({
    id: 'html-css-js',
    name: 'Plain HTML, CSS and JavaScript',
    category: 'web_frontend',
    type: 'language',
    licence: 'None',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['vanilla js', 'static html'],
    supportedProjectTypes: ['WEBSITE'],
    strengths: ['No build step, no framework churn, nothing to upgrade'],
    limitations: ['Becomes unmanageable once there is real application state'],
    learningBurden: 'low',
  }),

  /* ----------------------------------------------------------- backend */
  entry({
    id: 'nestjs',
    name: 'NestJS',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['nest'],
    strengths: ['Structure arrives decided, which matters on a team', 'First-class TypeScript'],
    limitations: ['More ceremony than Express for a small service'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'express',
    name: 'Express',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Minimal and universally understood'],
    limitations: ['Structure is left to you, which costs later on a larger codebase'],
    learningBurden: 'low',
  }),
  entry({
    id: 'django',
    name: 'Django',
    category: 'backend',
    type: 'framework',
    licence: 'BSD-3-Clause',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    secondaryCategories: ['authentication', 'content_management'],
    strengths: ['Admin, auth and ORM included', 'Very fast to a working back office'],
    limitations: ['Its conventions are hard to escape once you need something else'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'laravel',
    name: 'Laravel',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    secondaryCategories: ['authentication', 'background_jobs'],
    strengths: ['Broad batteries-included feature set', 'Very large PHP hiring pool'],
    limitations: ['PHP hosting conventions differ from the Node and Python ecosystems'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'spring-boot',
    name: 'Spring Boot',
    category: 'backend',
    type: 'framework',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['spring', 'java spring'],
    strengths: ['The default in regulated enterprise environments', 'Deep operational tooling'],
    limitations: ['Heavier runtime and slower iteration than the scripting ecosystems'],
    learningBurden: 'high',
  }),
  entry({
    id: 'fastapi',
    name: 'FastAPI',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Schema-first with generated OpenAPI', 'Natural fit next to Python ML code'],
    limitations: ['Smaller batteries-included surface than Django'],
    learningBurden: 'low',
  }),
  entry({
    id: 'dotnet',
    name: 'ASP.NET Core',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['.net', 'asp.net', 'dotnet core'],
    strengths: ['Strong performance', 'The natural choice in Microsoft-centric organisations'],
    limitations: ['Ecosystem assumptions lean towards Azure'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'go-backend',
    name: 'Go',
    category: 'backend',
    type: 'language',
    licence: 'BSD-3-Clause',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['golang'],
    strengths: ['Single static binary, trivial to deploy', 'Excellent concurrency story'],
    limitations: ['Less framework scaffolding, so more is written by hand'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'rails',
    name: 'Ruby on Rails',
    category: 'backend',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['rails', 'ruby on rails'],
    strengths: ['Very fast to a working CRUD application'],
    limitations: ['Smaller hiring pool than it once had'],
    learningBurden: 'medium',
  }),

  /* -------------------------------------------------- mobile & desktop */
  entry({
    id: 'flutter',
    name: 'Flutter',
    category: 'mobile_framework',
    type: 'framework',
    licence: 'BSD-3-Clause',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    secondaryCategories: ['desktop_framework'],
    supportedProjectTypes: [
      'MOBILE_APPLICATION',
      'CROSS_PLATFORM_MOBILE',
      'MULTI_PLATFORM_PRODUCT',
      'DESKTOP_APPLICATION',
    ],
    strengths: ['One codebase for Android and iOS', 'Consistent rendering across platforms'],
    limitations: ['Dart is a separate hiring pool', 'Large binaries relative to native'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'react-native',
    name: 'React Native',
    category: 'mobile_framework',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    supportedProjectTypes: [
      'MOBILE_APPLICATION',
      'CROSS_PLATFORM_MOBILE',
      'MULTI_PLATFORM_PRODUCT',
    ],
    strengths: ['Reuses React skills a web team already has'],
    limitations: ['Native modules are still needed for platform-specific work'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'kotlin-android',
    name: 'Kotlin (Android)',
    category: 'native_android',
    type: 'language',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['kotlin', 'jetpack compose'],
    supportedProjectTypes: ['ANDROID_APPLICATION', 'MOBILE_APPLICATION', 'MULTI_PLATFORM_PRODUCT'],
    strengths: ['Full access to every Android capability', 'Google’s first-class language'],
    limitations: ['Android only — an iOS build is a separate codebase'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'swift-ios',
    name: 'Swift (iOS)',
    category: 'native_ios',
    type: 'language',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['swift', 'swiftui'],
    supportedProjectTypes: ['IOS_APPLICATION', 'MOBILE_APPLICATION', 'MULTI_PLATFORM_PRODUCT'],
    strengths: ['Full access to every iOS capability', 'Apple’s first-class language'],
    limitations: [
      'iOS only — an Android build is a separate codebase',
      'Requires macOS hardware to build',
    ],
    learningBurden: 'medium',
  }),
  entry({
    id: 'electron',
    name: 'Electron',
    category: 'desktop_framework',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    supportedProjectTypes: ['DESKTOP_APPLICATION', 'MULTI_PLATFORM_PRODUCT'],
    strengths: ['Web skills produce a desktop application'],
    limitations: ['Large installers and high memory use'],
    learningBurden: 'low',
  }),
  entry({
    id: 'tauri',
    name: 'Tauri',
    category: 'desktop_framework',
    type: 'framework',
    licence: MIT,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    supportedProjectTypes: ['DESKTOP_APPLICATION', 'MULTI_PLATFORM_PRODUCT'],
    strengths: ['Far smaller and lighter than Electron'],
    limitations: ['Rust for the native layer', 'Younger ecosystem'],
    learningBurden: 'high',
  }),

  /* ---------------------------------------------------------- database */
  entry({
    id: 'postgresql',
    name: 'PostgreSQL',
    category: 'database',
    type: 'database',
    licence: 'PostgreSQL',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    aliases: ['postgres', 'psql'],
    secondaryCategories: ['vector_storage', 'search'],
    strengths: [
      'Transactional integrity for orders, payments and ledgers',
      'JSON, full-text search and vectors without a second datastore',
    ],
    limitations: ['Horizontal write scaling needs deliberate work'],
    operationalComplexity: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'mysql',
    name: 'MySQL',
    category: 'database',
    type: 'database',
    licence: 'GPL-2.0 / commercial',
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    aliases: ['mariadb'],
    commercialUseNote:
      'The community edition is GPL. Oracle sells a commercial licence for cases where GPL is unacceptable.',
    strengths: ['Ubiquitous hosting support', 'Very large operator hiring pool'],
    limitations: ['Fewer advanced features than PostgreSQL'],
    operationalComplexity: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'mongodb',
    name: 'MongoDB',
    category: 'database',
    type: 'database',
    licence: 'SSPL-1.0',
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    aliases: ['mongo'],
    commercialUseNote:
      'SSPL is not OSI-approved and constrains offering MongoDB itself as a service. Normal application use is unaffected; check it if you are building a hosting product.',
    strengths: ['Flexible documents suit evolving or irregular data'],
    limitations: ['Multi-document transactions are possible but not the natural grain'],
    operationalComplexity: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'sqlite',
    name: 'SQLite',
    category: 'database',
    type: 'database',
    licence: 'Public domain',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['No server to run', 'Ideal embedded in desktop and mobile applications'],
    limitations: ['Not for concurrent multi-writer server workloads'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'sql-server',
    name: 'Microsoft SQL Server',
    category: 'database',
    type: 'database',
    licence: 'Commercial',
    costPosture: 'COMMERCIAL',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    openSource: false,
    aliases: ['mssql', 'sqlserver'],
    commercialUseNote:
      'Per-core or per-server licensing. Confirm the client already holds licences before assuming this is free to them.',
    strengths: ['Deep integration with the Microsoft estate'],
    limitations: ['Licence cost is material and must be budgeted'],
    operationalComplexity: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'oracle-db',
    name: 'Oracle Database',
    category: 'database',
    type: 'database',
    licence: 'Commercial',
    costPosture: 'COMMERCIAL',
    maturity: 'established',
    selfHostable: true,
    openSource: false,
    commercialUseNote:
      'Licensing is expensive and audit-sensitive. Only select this where the client already runs it.',
    strengths: ['Entrenched in large enterprises with existing investment'],
    limitations: ['Cost and licensing complexity'],
    operationalComplexity: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'dynamodb',
    name: 'Amazon DynamoDB',
    category: 'database',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    commercialUseNote: 'Billed per request and per stored GB. Costs follow traffic.',
    // The clash with a "must be self-hosted" *constraint* is not expressible
    // here — `selfHostable: false` states it and the constraint rules read it.
    // A clash with another chosen technology is.
    incompatibleWith: [
      {
        technologyId: 'on-premise',
        reason:
          'DynamoDB runs only inside AWS and cannot be deployed on the client’s own hardware.',
      },
      { technologyId: 'azure', reason: 'DynamoDB is an AWS service.' },
      { technologyId: 'gcp', reason: 'DynamoDB is an AWS service.' },
    ],
    strengths: ['No servers to operate', 'Predictable latency at scale'],
    limitations: ['AWS lock-in', 'Query patterns must be designed up front'],
    infrastructureBurden: 'low',
    learningBurden: 'high',
  }),

  /* ------------------------------------------- cache, search, vectors */
  entry({
    id: 'redis',
    name: 'Redis',
    category: 'cache',
    type: 'database',
    licence: 'RSALv2 / SSPL',
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    secondaryCategories: ['message_queue', 'background_jobs'],
    commercialUseNote:
      'Redis relicensed away from BSD in 2024. Valkey is the BSD-licensed fork if that matters to the client.',
    strengths: ['Fast, simple and well understood'],
    limitations: ['Another service to run, monitor and back up'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'valkey',
    name: 'Valkey',
    category: 'cache',
    type: 'database',
    licence: 'BSD-3-Clause',
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    secondaryCategories: ['message_queue'],
    strengths: ['Redis-compatible under a permissive licence'],
    limitations: ['Younger project than Redis itself'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'elasticsearch',
    name: 'Elasticsearch',
    category: 'search',
    type: 'service',
    licence: 'Elastic-2.0 / SSPL',
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    commercialUseNote:
      'Not OSI open source since 7.11. OpenSearch is the Apache-2.0 fork. Check which the client can accept.',
    strengths: ['Mature full-text search with faceting and aggregation'],
    limitations: ['Substantial memory footprint and real operational burden'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'opensearch',
    name: 'OpenSearch',
    category: 'search',
    type: 'service',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Apache-licensed Elasticsearch fork'],
    limitations: ['Same operational weight as Elasticsearch'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'meilisearch',
    name: 'Meilisearch',
    category: 'search',
    type: 'service',
    licence: MIT,
    costPosture: 'MIXED',
    maturity: 'growing',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Fast to stand up', 'Good typo tolerance out of the box'],
    limitations: ['Less powerful aggregation than Elasticsearch'],
    operationalComplexity: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'pgvector',
    name: 'pgvector',
    category: 'vector_storage',
    type: 'library',
    licence: 'PostgreSQL',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    // The only reason to choose pgvector is that PostgreSQL is already there.
    // Paired with any other database it is not a trade-off, it is a mistake.
    incompatibleWith: [
      { technologyId: 'mysql', reason: 'pgvector is a PostgreSQL extension.' },
      { technologyId: 'mongodb', reason: 'pgvector is a PostgreSQL extension.' },
      { technologyId: 'sqlite', reason: 'pgvector is a PostgreSQL extension.' },
      { technologyId: 'sql-server', reason: 'pgvector is a PostgreSQL extension.' },
      { technologyId: 'oracle-db', reason: 'pgvector is a PostgreSQL extension.' },
      { technologyId: 'dynamodb', reason: 'pgvector is a PostgreSQL extension.' },
    ],
    strengths: [
      'Vectors in the database you already run — no second datastore to operate',
      'Joins vectors against relational data in one query',
    ],
    limitations: ['Slower than a dedicated vector store at very large scale'],
    operationalComplexity: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'qdrant',
    name: 'Qdrant',
    category: 'vector_storage',
    type: 'service',
    licence: APACHE,
    costPosture: 'MIXED',
    maturity: 'growing',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Purpose-built vector search with filtering'],
    limitations: ['An additional service to operate — justify it before adding it'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),

  /* ---------------------------------------------------------- storage */
  entry({
    id: 'minio',
    name: 'MinIO',
    category: 'object_storage',
    type: 'service',
    licence: 'AGPL-3.0',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    commercialUseNote:
      'AGPL. Fine as a deployed service; take advice before linking it into distributed code.',
    strengths: ['S3-compatible without a cloud account'],
    limitations: ['You operate the durability story yourself'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 's3',
    name: 'Amazon S3',
    category: 'object_storage',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    commercialUseNote: 'Billed per GB stored, per request and per GB egress.',
    incompatibleWith: [
      {
        technologyId: 'on-premise',
        reason:
          'S3 is an AWS service; storing on the client’s own hardware means a different store.',
      },
    ],
    strengths: ['Effectively unlimited and durable', 'Nothing to operate'],
    limitations: ['Egress charges surprise people', 'AWS account required'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),

  /* ------------------------------------------- auth, gateway, realtime */
  entry({
    id: 'keycloak',
    name: 'Keycloak',
    category: 'authentication',
    type: 'service',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    secondaryCategories: ['authorization'],
    strengths: ['Full OIDC and SAML identity provider you host yourself'],
    limitations: ['Non-trivial to operate and upgrade'],
    operationalComplexity: 'high',
    infrastructureBurden: 'medium',
    learningBurden: 'high',
  }),
  entry({
    id: 'auth0',
    name: 'Auth0',
    category: 'authentication',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    commercialUseNote: 'Priced per monthly active user. Model the cost at expected scale early.',
    strengths: ['Social, enterprise and passwordless login without building any of it'],
    limitations: ['Per-user cost grows with success', 'Identity data lives with the vendor'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'app-native-auth',
    name: 'Application-native authentication',
    category: 'authentication',
    type: 'library',
    licence: 'Varies',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['built-in auth', 'custom auth'],
    strengths: ['No extra service, no per-user cost', 'Adequate for a single application'],
    limitations: ['You own password handling, sessions and account recovery'],
    learningBurden: 'low',
  }),
  entry({
    id: 'casbin',
    name: 'Casbin',
    category: 'authorization',
    type: 'library',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    strengths: ['Policy-based access control as a library rather than a service'],
    limitations: ['Policy modelling takes real design effort'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'kong',
    name: 'Kong',
    category: 'api_gateway',
    type: 'service',
    licence: APACHE,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Rate limiting, auth and routing in front of many services'],
    limitations: ['Adds a hop and a component; unnecessary in front of one application'],
    operationalComplexity: 'high',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'nginx',
    name: 'nginx',
    category: 'api_gateway',
    type: 'service',
    licence: 'BSD-2-Clause',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    secondaryCategories: ['hosting'],
    strengths: ['Proven reverse proxy and TLS terminator', 'Negligible resource use'],
    limitations: ['Not a full API management product'],
    operationalComplexity: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'socket-io',
    name: 'Socket.IO',
    category: 'realtime',
    type: 'library',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Bidirectional messaging with reconnection handled'],
    limitations: ['Sticky sessions or an adapter are needed once there is more than one node'],
    learningBurden: 'low',
  }),
  entry({
    id: 'server-sent-events',
    name: 'Server-Sent Events',
    category: 'realtime',
    type: 'protocol',
    licence: 'Open standard',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['sse'],
    strengths: ['Plain HTTP, no extra dependency, ideal for one-way updates'],
    limitations: ['Server to client only'],
    learningBurden: 'low',
  }),

  /* -------------------------------------------------- queues and jobs */
  entry({
    id: 'rabbitmq',
    name: 'RabbitMQ',
    category: 'message_queue',
    type: 'service',
    licence: 'MPL-2.0',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Mature broker with rich routing'],
    limitations: ['A broker to operate, monitor and upgrade'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'kafka',
    name: 'Apache Kafka',
    category: 'message_queue',
    type: 'service',
    licence: APACHE,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Durable, replayable, very high throughput event log'],
    limitations: [
      'Heavy to operate — genuinely justified only by event-streaming or replay requirements',
    ],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'db-backed-jobs',
    name: 'Database-backed job queue',
    category: 'background_jobs',
    type: 'library',
    licence: 'Varies',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['database queue', 'polling worker'],
    strengths: ['No new infrastructure', 'Adequate for most background work'],
    limitations: ['Not for very high throughput fan-out'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'bullmq',
    name: 'BullMQ',
    category: 'background_jobs',
    type: 'library',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    incompatibleWith: [
      { technologyId: 'django', reason: 'BullMQ is a Node library and cannot run jobs in Python.' },
      {
        technologyId: 'fastapi',
        reason: 'BullMQ is a Node library and cannot run jobs in Python.',
      },
      { technologyId: 'laravel', reason: 'BullMQ is a Node library and cannot run jobs in PHP.' },
      {
        technologyId: 'spring-boot',
        reason: 'BullMQ is a Node library and cannot run jobs in Java.',
      },
      { technologyId: 'rails', reason: 'BullMQ is a Node library and cannot run jobs in Ruby.' },
      { technologyId: 'dotnet', reason: 'BullMQ is a Node library and cannot run jobs in .NET.' },
      { technologyId: 'go-backend', reason: 'BullMQ is a Node library and cannot run jobs in Go.' },
    ],
    strengths: ['Retries, scheduling and concurrency handled'],
    limitations: ['Requires Redis, so it brings a service with it'],
    learningBurden: 'low',
  }),
  entry({
    id: 'celery',
    name: 'Celery',
    category: 'background_jobs',
    type: 'library',
    licence: 'BSD-3-Clause',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    incompatibleWith: [
      { technologyId: 'nestjs', reason: 'Celery is a Python library and cannot run jobs in Node.' },
      {
        technologyId: 'express',
        reason: 'Celery is a Python library and cannot run jobs in Node.',
      },
      { technologyId: 'laravel', reason: 'Celery is a Python library and cannot run jobs in PHP.' },
      { technologyId: 'dotnet', reason: 'Celery is a Python library and cannot run jobs in .NET.' },
    ],
    strengths: ['The established Python task queue'],
    limitations: ['Requires a broker'],
    learningBurden: 'medium',
  }),

  /* --------------------------------------------------------- payments */
  entry({
    id: 'stripe',
    name: 'Stripe',
    category: 'payment',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    commercialUseNote:
      'Per-transaction fee. Availability and pricing vary by country — confirm for the client’s market.',
    strengths: ['Excellent developer experience', 'Subscriptions, invoicing and tax included'],
    limitations: ['Not available in every country', 'Per-transaction cost'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'razorpay',
    name: 'Razorpay',
    category: 'payment',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote: 'Per-transaction fee. Primarily India.',
    strengths: ['Strong local payment-method coverage in India'],
    limitations: ['Regional'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'paypal',
    name: 'PayPal',
    category: 'payment',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote: 'Per-transaction fee.',
    strengths: ['Buyer familiarity in many markets'],
    limitations: ['Integration ergonomics lag the newer providers'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),

  /* ------------------------------------------------------------- AI */
  entry({
    id: 'ollama',
    name: 'Ollama',
    category: 'ai_runtime',
    type: 'runtime',
    licence: MIT,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    strengths: ['Runs open models on your own hardware', 'No per-token cost'],
    limitations: ['Throughput is bounded by the hardware you own'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'vllm',
    name: 'vLLM',
    category: 'ai_runtime',
    type: 'runtime',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    strengths: ['High-throughput self-hosted serving'],
    limitations: ['Wants a GPU to be worth it'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'openai-api',
    name: 'OpenAI API',
    category: 'ai_model',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote:
      'Billed per token. Client data leaves their infrastructure — check this against any data-residency requirement.',
    strengths: ['Strong models with no infrastructure to run'],
    limitations: ['Per-token cost', 'Data leaves the client’s control'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'anthropic-api',
    name: 'Anthropic API',
    category: 'ai_model',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote:
      'Billed per token. Client data leaves their infrastructure — check this against any data-residency requirement.',
    strengths: ['Strong models with long context and no infrastructure to run'],
    limitations: ['Per-token cost', 'Data leaves the client’s control'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'open-weights-model',
    name: 'Open-weights model (Llama, Qwen, Mistral)',
    category: 'ai_model',
    type: 'model',
    licence: 'Varies by model',
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    aliases: ['llama', 'qwen', 'mistral', 'local model'],
    commercialUseNote:
      'Licences differ per model and some restrict commercial use at scale. Check the specific model before committing.',
    strengths: ['No per-token cost', 'Data never leaves the client’s infrastructure'],
    limitations: ['Weaker than the leading hosted models', 'Needs hardware'],
    infrastructureBurden: 'high',
    learningBurden: 'medium',
  }),

  /* -------------------------------------- hosting, containers, CI/CD */
  entry({
    id: 'aws',
    name: 'Amazon Web Services',
    category: 'hosting',
    type: 'platform',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    aliases: ['amazon web services'],
    commercialUseNote: 'Billed by consumption across every service used.',
    strengths: ['The broadest managed-service catalogue'],
    limitations: [
      'Cost control needs active attention',
      'Deep lock-in when managed services are used',
    ],
    infrastructureBurden: 'low',
    learningBurden: 'high',
  }),
  entry({
    id: 'azure',
    name: 'Microsoft Azure',
    category: 'hosting',
    type: 'platform',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    commercialUseNote:
      'Billed by consumption. Often already procured in Microsoft-centric clients.',
    strengths: ['Natural fit alongside an existing Microsoft estate'],
    limitations: ['Cost control needs active attention'],
    infrastructureBurden: 'low',
    learningBurden: 'high',
  }),
  entry({
    id: 'gcp',
    name: 'Google Cloud Platform',
    category: 'hosting',
    type: 'platform',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    managedServiceAvailable: true,
    openSource: false,
    aliases: ['google cloud'],
    commercialUseNote: 'Billed by consumption.',
    strengths: ['Strong data and ML services'],
    limitations: ['Smaller service catalogue than AWS'],
    infrastructureBurden: 'low',
    learningBurden: 'high',
  }),
  entry({
    id: 'vps-hosting',
    name: 'Virtual private server',
    category: 'hosting',
    type: 'platform',
    licence: 'Varies',
    costPosture: 'COMMERCIAL',
    maturity: 'established',
    selfHostable: true,
    aliases: ['vps', 'hetzner', 'digitalocean', 'linode'],
    commercialUseNote:
      'A flat monthly fee per server. Predictable and usually the cheapest option.',
    strengths: ['Predictable cost', 'No managed-service lock-in'],
    limitations: ['You operate everything: patching, backups, failover'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'on-premise',
    name: 'Client’s own infrastructure',
    category: 'hosting',
    type: 'platform',
    licence: 'None',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['on-prem', 'on premise', 'self-hosted'],
    strengths: ['Data never leaves the client’s premises', 'No cloud spend'],
    limitations: ['Capacity, availability and disaster recovery are the client’s to provide'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'medium',
  }),
  entry({
    id: 'docker',
    name: 'Docker',
    category: 'containerization',
    type: 'tool',
    licence: APACHE,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    commercialUseNote:
      'The engine is free. Docker Desktop requires a paid subscription for larger companies.',
    strengths: ['Reproducible environments from development to production'],
    limitations: ['One more thing in the build pipeline'],
    operationalComplexity: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'kubernetes',
    name: 'Kubernetes',
    category: 'containerization',
    type: 'platform',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    aliases: ['k8s'],
    strengths: ['Orchestration, scaling and self-healing for many services'],
    limitations: [
      'Substantial permanent operational cost — justified by scale or multi-service topology, not by ambition',
    ],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
  entry({
    id: 'github-actions',
    name: 'GitHub Actions',
    category: 'ci_cd',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'FREE_TIER_AVAILABLE',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote:
      'Generous free minutes for public repositories; private repositories consume a quota, then bill per minute.',
    strengths: ['No separate CI system when the code is already on GitHub'],
    limitations: ['Tied to GitHub'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'gitlab-ci',
    name: 'GitLab CI',
    category: 'ci_cd',
    type: 'service',
    licence: MIT,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    strengths: ['Can be self-hosted with the rest of GitLab'],
    limitations: ['Self-hosted runners are yours to operate'],
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'jenkins',
    name: 'Jenkins',
    category: 'ci_cd',
    type: 'service',
    licence: MIT,
    costPosture: FREE,
    maturity: 'legacy',
    selfHostable: true,
    strengths: ['Self-hosted and endlessly extensible'],
    limitations: ['Plugin maintenance is a standing cost'],
    operationalComplexity: 'high',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),

  /* ------------------------------------- observability and analytics */
  entry({
    id: 'prometheus-grafana',
    name: 'Prometheus and Grafana',
    category: 'monitoring',
    type: 'service',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['prometheus', 'grafana'],
    strengths: ['The self-hosted metrics standard', 'No per-host billing'],
    limitations: ['You run and scale it'],
    operationalComplexity: 'medium',
    infrastructureBurden: 'medium',
    learningBurden: 'medium',
  }),
  entry({
    id: 'datadog',
    name: 'Datadog',
    category: 'monitoring',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'USAGE_BASED',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    commercialUseNote: 'Billed per host and per ingested GB. Costs rise quickly with hosts.',
    strengths: ['Metrics, traces and logs in one place with nothing to run'],
    limitations: ['Cost scales with infrastructure'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'sentry',
    name: 'Sentry',
    category: 'monitoring',
    type: 'service',
    licence: 'FSL / BSL',
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Error tracking with the stack trace and release attached'],
    limitations: ['Self-hosting it is a real deployment in its own right'],
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'opensearch-logs',
    name: 'OpenSearch for logs',
    category: 'logging',
    type: 'service',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['elk', 'opensearch dashboards'],
    strengths: ['Searchable log aggregation you own'],
    limitations: ['Storage and memory hungry'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'medium',
  }),
  entry({
    id: 'structured-file-logs',
    name: 'Structured file logs',
    category: 'logging',
    type: 'library',
    licence: 'Varies',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['json logs', 'pino', 'winston'],
    strengths: ['No infrastructure at all', 'Enough for a single-service deployment'],
    limitations: ['No aggregation across hosts'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),
  entry({
    id: 'plausible',
    name: 'Plausible Analytics',
    category: 'analytics',
    type: 'service',
    licence: 'AGPL-3.0',
    costPosture: 'MIXED',
    maturity: 'growing',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Privacy-preserving and self-hostable', 'No cookie banner needed'],
    limitations: ['Less depth than the large analytics suites'],
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'analytics',
    type: 'service',
    licence: 'Proprietary',
    costPosture: 'FREE_TIER_AVAILABLE',
    maturity: 'established',
    selfHostable: false,
    openSource: false,
    aliases: ['ga4'],
    commercialUseNote:
      'Free at typical volumes. Has drawn regulatory attention in the EU over data transfer — check against any privacy requirement.',
    strengths: ['Free and familiar to marketing teams'],
    limitations: ['Privacy and consent obligations follow it'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),

  /* -------------------------------------------- testing and security */
  entry({
    id: 'playwright',
    name: 'Playwright',
    category: 'testing',
    type: 'tool',
    licence: APACHE,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Real-browser end-to-end testing across engines'],
    limitations: ['Slower than unit tests; needs deliberate CI capacity'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'jest',
    name: 'Jest',
    category: 'testing',
    type: 'tool',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['The established JavaScript unit-test runner'],
    limitations: ['ESM support still needs care'],
    learningBurden: 'low',
  }),
  entry({
    id: 'vitest',
    name: 'Vitest',
    category: 'testing',
    type: 'tool',
    licence: MIT,
    costPosture: FREE,
    maturity: 'growing',
    selfHostable: true,
    strengths: ['Fast, and native ESM'],
    limitations: ['Younger than Jest'],
    learningBurden: 'low',
  }),
  entry({
    id: 'pytest',
    name: 'pytest',
    category: 'testing',
    type: 'tool',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['The Python testing standard'],
    limitations: [],
    learningBurden: 'low',
  }),
  entry({
    id: 'clamav',
    name: 'ClamAV',
    category: 'security_tooling',
    type: 'tool',
    licence: 'GPL-2.0',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Self-hosted malware scanning for uploads'],
    limitations: ['Detection lags commercial engines'],
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'dependency-audit',
    name: 'Dependency vulnerability scanning',
    category: 'security_tooling',
    type: 'tool',
    licence: 'Varies',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['npm audit', 'dependabot', 'trivy'],
    strengths: ['Catches known vulnerable dependencies in CI'],
    limitations: ['Known vulnerabilities only'],
    learningBurden: 'low',
  }),

  /* ------------------------------------------------ content and CMS */
  entry({
    id: 'wordpress',
    name: 'WordPress',
    category: 'content_management',
    type: 'platform',
    licence: 'GPL-2.0',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    supportedProjectTypes: ['WEBSITE', 'ECOMMERCE_PLATFORM'],
    strengths: ['Editors already know it', 'Vast plugin and theme ecosystem'],
    limitations: ['Plugin sprawl becomes a security and upgrade burden'],
    operationalComplexity: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'strapi',
    name: 'Strapi',
    category: 'content_management',
    type: 'framework',
    licence: MIT,
    costPosture: 'MIXED',
    maturity: 'growing',
    selfHostable: true,
    strengths: ['Headless CMS with a generated API'],
    limitations: ['Upgrades between major versions take work'],
    infrastructureBurden: 'medium',
    learningBurden: 'low',
  }),
  entry({
    id: 'markdown-content',
    name: 'Markdown files in the repository',
    category: 'content_management',
    type: 'tool',
    licence: 'None',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    supportedProjectTypes: ['WEBSITE'],
    strengths: ['No CMS to run, host or patch', 'Content is versioned with the code'],
    limitations: ['Non-technical editors need a git-backed editing tool'],
    infrastructureBurden: 'low',
    learningBurden: 'low',
  }),

  /* ---------------------------------------- integration and data work */
  entry({
    id: 'rest-api',
    name: 'REST over HTTP',
    category: 'integrations',
    type: 'protocol',
    licence: 'Open standard',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['rest', 'http api'],
    strengths: ['Universally supported', 'Debuggable with ordinary tools'],
    limitations: ['No built-in schema contract without OpenAPI discipline'],
    learningBurden: 'low',
  }),
  entry({
    id: 'graphql',
    name: 'GraphQL',
    category: 'integrations',
    type: 'protocol',
    licence: MIT,
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    strengths: ['Clients fetch exactly what they need'],
    limitations: ['Caching and rate limiting are harder than with REST'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'soap',
    name: 'SOAP',
    category: 'integrations',
    type: 'protocol',
    licence: 'Open standard',
    costPosture: FREE,
    maturity: 'legacy',
    selfHostable: true,
    strengths: ['Still the only interface some enterprise systems expose'],
    limitations: ['Verbose and awkward from modern stacks'],
    learningBurden: 'medium',
  }),
  entry({
    id: 'sftp-exchange',
    name: 'Scheduled SFTP file exchange',
    category: 'integrations',
    type: 'protocol',
    licence: 'Open standard',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['sftp', 'file drop'],
    strengths: ['Works with systems that offer nothing else'],
    limitations: ['Batch, not real time', 'Error handling is yours to build'],
    learningBurden: 'low',
  }),
  entry({
    id: 'etl-scripts',
    name: 'Scheduled transformation jobs',
    category: 'data_processing',
    type: 'tool',
    licence: 'Varies',
    costPosture: FREE,
    maturity: 'established',
    selfHostable: true,
    aliases: ['etl', 'batch jobs'],
    strengths: ['No pipeline platform to operate', 'Fits most migration workloads'],
    limitations: ['Orchestration and retries are yours to write'],
    learningBurden: 'low',
  }),
  entry({
    id: 'airflow',
    name: 'Apache Airflow',
    category: 'data_processing',
    type: 'platform',
    licence: APACHE,
    costPosture: 'MIXED',
    maturity: 'established',
    selfHostable: true,
    managedServiceAvailable: true,
    strengths: ['Dependency-aware scheduling with visibility into runs'],
    limitations: ['A platform in its own right — justify it before adding it'],
    operationalComplexity: 'high',
    infrastructureBurden: 'high',
    learningBurden: 'high',
  }),
];

/** Fast lookup by id. Built once. */
export const CATALOG_BY_ID: ReadonlyMap<string, CatalogEntry> = new Map(
  TECHNOLOGY_CATALOG.map((item) => [item.id, item]),
);

export function findTechnology(id: string): CatalogEntry | undefined {
  return CATALOG_BY_ID.get(id);
}

/**
 * Resolve a typed name to a catalogue entry.
 *
 * Used when a user types a technology rather than picking one, so *"postgres"*
 * and *"PostgreSQL"* reach the same entry and inherit its reviewed facts
 * instead of becoming a custom entry with none.
 */
export function resolveByName(name: string): CatalogEntry | undefined {
  const needle = name.trim().toLowerCase();

  if (!needle) {
    return undefined;
  }

  return TECHNOLOGY_CATALOG.find(
    (item) =>
      item.id === needle ||
      item.name.toLowerCase() === needle ||
      item.aliases.some((alias) => alias.toLowerCase() === needle),
  );
}
